name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.6
      - name: Restore CI Cache
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09 # tag=v3.0.2
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-16.6-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --immutable
      - name: Build Code
        run: yarn build
      - name: Build Binaries
        run: npx pkg dist/cli.js --C GZip --public -o rspell -t macos,windows,linux
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            rspell-linux
            rspell-macos
            rspell-win.exe
